spec:
  initContainers:
    copy-dags-to-bd:
      image:
        repository: hellodata-ws-boilerplate
        pullPolicy: IfNotPresent
        tag: "0.1.0-a.1"
      resources: {}

      volumeMounts:
        - name: storage-hellodata
          type: external
          path: /storage
      command: ["/bin/sh", "-c"]
      args:
        [
          "mkdir -p /storage/${datadomain}/dags/${workspace}/ && rm -rf /storage/${datadomain}/dags/${workspace}/* && cp -a /opt/airflow/airflow_home/dags/*.py /storage/${datadomain}/dags/${workspace}/",
        ]

  containers:
    - name: ws-boilerplate
      image: hellodata-ws-boilerplate:0.1.0-a.1
      imagePullPolicy: Always

# ENV Variables see in deployment/env
