version: '3.8'
services:
  app:
    build:
      context: ..
      dockerfile: ../Dockerfile
    env_file:
      - ../deployment/local/env  # Loads your environment variables
    environment:
      #- DATABASE_URL=postgresql://${POSTGRES_USERNAME_HD}:${POSTGRES_PASSWORD_HD}@${POSTGRES_HOST_HD}:${POSTGRES_PORT_HD}/${POSTGRES_DATABASE_HD}
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tierstatistik
    volumes:
      - ../src:/workspace # Maps the parent directory to /workspace in the container
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      # POSTGRES_DB: POSTGRES_DATABASE_HD
      # POSTGRES_USER: POSTGRES_USERNAME_HD
      # POSTGRES_PASSWORD: POSTGRES_PASSWORD_HD
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
