showcase_tierstatistik:
  target: test
  outputs:

    test: 
      type: postgres
      threads: 1
      host: "host.docker.internal"
      port: 5432
      user: "sspaeti"
      pass: "postgres"
      dbname: "tierstatistik"
      schema: "tierstatistik"

